pgadmin4:
  extraEnvs:
    - name: PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY
      value: "False"
    - name: PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS
      value: "true"
    - name: PGADMIN_CONFIG_ALLOWED_EMAIL_DOMAINS
      value: "k8ground.test"
    - name: PGADMIN_DEFAULT_EMAIL
      value: admin@k8ground.test  # Using a standard domain for now
    - name: PGADMIN_DEFAULT_PASSWORD
      value: admin
  
  ingress:
    enabled: true
    hosts:
      - host: pgadmin.k8ground.test
        paths:
          - path: /
            pathType: Prefix
  
  serverDefinitions:
    enabled: true
    servers:
      1:
        Name: Kubernetes PostgreSQL
        Group: Kubernetes
        Host: postgres-postgresql.dev-stage.svc.cluster.local
        Port: 5432
        MaintenanceDB: app_db
        Username: admin
        Password: admin
        SSLMode: prefer