keycloak:
  # Basic configuration
  image:
    tag: 26.2.5  # Use a version compatible with Bitnami's chart
  
  # Admin credentials
  auth:
    adminUser: admin
    adminPassword: admin
  
  # Resources
  resources:
    limits:
      memory: 1024Mi
      cpu: 1000m
    requests:
      memory: 512Mi
      cpu: 250m

  # # Database configuration
  # externalDatabase:
  #   host: postgres-postgresql.dev-stage.svc.cluster.local
  #   port: 5432
  #   username: admin
  #   password: admin
  #   database: keycloak

  # Add extra environment variables to force database configuration
  extraEnvVars:
    - name: KEYCLOAK_DATABASE_HOST
      value: "postgres-postgresql.dev-stage.svc.cluster.local"
    - name: KEYCLOAK_DATABASE_PORT
      value: "5432"
    - name: KEYCLOAK_DATABASE_USER
      value: "admin"
    - name: KEYCLOAK_DATABASE_PASSWORD
      value: "admin"
    - name: KEYCLOAK_DATABASE_NAME
      value: "keycloak"
  
  # Disable embedded PostgreSQL
  postgresql:
    enabled: false
  
  # Configuration parameters
  production: false  # Use false for development environments
  proxy: edge
  
  # Ingress configuration
  ingress:
    enabled: true
    hostname: keycloak.k8ground.test
    path: /
    pathType: Prefix
  
  # Service configuration
  service:
    type: ClusterIP
    ports:
      http: 80
  
  # Probes for Bitnami chart
  startupProbe:
    enabled: true
    failureThreshold: 60
    initialDelaySeconds: 30
    periodSeconds: 10
  
  livenessProbe:
    enabled: true
    initialDelaySeconds: 300
    periodSeconds: 30
  
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
  
  # Pod configuration  
  podAnnotations:
    app.kubernetes.io/part-of: keycloak
    app.kubernetes.io/component: auth