keycloak:
  # Basic configuration
  image:
    tag: 21.1.2
  
  # Admin credentials
  auth:
    adminUser: admin
    adminPassword: admin
  
  # Resources - increased for stability
  resources:
    limits:
      memory: 1024Mi
      cpu: 1000m
    requests:
      memory: 512Mi
      cpu: 250m
  
  # Database configuration
  externalDatabase:
    host: postgres-postgresql.dev-stage.svc.cluster.local
    port: 5432
    user: admin
    database: keycloak
    password: admin
  
  # Add explicit database configuration
  extraEnv:
    - name: KC_DB
      value: "postgres"
    - name: KC_DB_URL_HOST
      value: "postgres-postgresql.dev-stage.svc.cluster.local"
    - name: KC_DB_URL_DATABASE
      value: "keycloak"
    - name: KC_DB_USERNAME
      value: "admin"
    - name: KC_DB_PASSWORD
      value: "admin"
    - name: KC_HEALTH_ENABLED
      value: "true"
    - name: KEYCLOAK_LOGLEVEL
      value: "DEBUG"
  
  # Updated startup arguments - this is important for Keycloak v21+
  extraStartupArgs: >-
    --optimized --http-enabled=true --hostname-strict=false --hostname-strict-https=false
  
  # Ingress configuration
  ingress:
    enabled: true
    rules:
      - host: keycloak.k8ground.test
        paths:
          - path: /
            pathType: Prefix
  
  # Pod configuration  
  podAnnotations:
    app.kubernetes.io/part-of: keycloak
    app.kubernetes.io/component: auth
  
  # Service configuration
  service:
    type: ClusterIP
    port: 80
  
  # Add proper startup probe
  startupProbe:
    enabled: true
    failureThreshold: 60  # Allow more time for startup
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 3
    
  # Use standard readiness/liveness probes
  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 30
  
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 30