applications:
  # Simple nginx app
  - name: dummy-nginx-develop
    namespace: ai4-apps-develop-kihub
    repoURL: https://github.com/ruslan-s/k8ground.git 
    path: argo-apps/apps/nginx

  - name: dummy-nginx-77777
    namespace: stage
    repoURL: https://github.com/ruslan-s/k8ground.git 
    path: argo-apps/apps/nginx
    targetRevision: stage

  # PostgreSQL database (DEV Stage)
  - name: postgres
    namespace: dev-stage
    repoURL: https://github.com/ruslan-s/k8ground.git 
    path: argo-apps/apps/postgres

  # pgAdmin for managing PostgreSQL databases
  - name: pgadmin
    namespace: dev-stage
    repoURL: https://github.com/ruslan-s/k8ground.git
    path: argo-apps/apps/pgAdmin

  # Keycloak for authentication
  - name: keycloak
    namespace: dg-auth
    repoURL: https://github.com/ruslan-s/k8ground.git
    path: argo-apps/apps/keycloak

  # Add more apps here later
  # - name: another-app
  #   namespace: another-ns
  #   ...