applications:
  # Simple nginx app
  - name: app-test-dummy-nginx
    namespace: playground
    repoURL: https://github.com/ruslan-s/k8ground.git 
    path: argo-apps/apps/nginx

  # Add more apps here later
  # - name: another-app
  #   namespace: another-ns
  #   ...