server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - argocd.k8ground.test
      - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: argocd-server
              port:
                number: 80
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
      traefik.ingress.kubernetes.io/router.rule: Host(`argocd.k8ground.test`)

  # ÐžDisable HTTPS for test environment
  extraArgs:
    - --insecure

# Namespace definition
global:
  namespace: dg-argocd
