# Default values - can be overridden by app-of-apps
nginx:
  image:
    registry: docker.io
    repository: bitnami/nginx
    tag: "1.25.4-debian-12-r6"  # Default image tag
  replicaCount: 1         # Default replicas
