# Default values - can be overridden by app-of-apps
nginx:
  image:
    registry: docker.io
    repository: nginx
    tag: "1.25.2-alpine"  # Default image tag
  replicaCount: 5         # Default replicas
